application:
  name: play-with-qovery
  project: vote
  cloud_region: aws/eu-west-3
  publicly_accessible: true
routers:
- name: main
  routes:
  - application_name: play-with-qovery
    paths:
    - /
